on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: pkgconfig(libffi) glibc-langpack-cs
    strategy:
      matrix:
        tox_env: [py37, py38, py39, py310, lint]

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
